import { writeFileSync } from "fs";
import { join } from "path";

import yaml from "js-yaml";

import { getBrowserHistory } from "utils/browser-history";
import { CONF_DIR } from "utils/config/config";
import createLogger from "utils/logger";

const logger = createLogger("browserHistorySync");

/**
 * POST /api/browser-history/sync
 *
 * Reads browser history, categorizes sites, and generates a
 * "Browser History" group in bookmarks.yaml.
 *
 * Query params:
 *   browser - Which browser to read (default: "auto")
 *   limit   - Max sites per category (default: 5)
 *   mode    - "append" (add to existing bookmarks) or "replace" (overwrite)
 */
export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed. Use POST." });
  }

  try {
    const { browser = "auto", limit = "5", mode = "append" } = req.query;
    const limitNum = parseInt(limit, 10);

    const { topSites, categorized } = getBrowserHistory({
      browser,
      topLimit: 20,
      recentLimit: 10,
    });

    if (!topSites || topSites.length === 0) {
      return res.status(200).json({ status: "no_history", message: "No browser history found" });
    }

    // Build bookmark groups from categorized data
    const historyBookmarks = [];

    // Top Sites group (always first)
    const topGroup = { "Top Sites": [] };
    for (const site of topSites.slice(0, limitNum)) {
      topGroup["Top Sites"].push({
        [site.title]: [{ abbr: site.abbr, href: site.url }],
      });
    }
    historyBookmarks.push(topGroup);

    // Category groups
    for (const [category, sites] of Object.entries(categorized)) {
      const group = { [category]: [] };
      for (const site of sites.slice(0, limitNum)) {
        group[category].push({
          [site.title]: [{ abbr: site.abbr, href: site.url }],
        });
      }
      // Only add if not already covered by Top Sites
      if (group[category].length > 0) {
        historyBookmarks.push(group);
      }
    }

    // Read existing bookmarks
    const bookmarksPath = join(CONF_DIR, "bookmarks.yaml");
    let existingBookmarks = [];

    if (mode === "append") {
      try {
        const { readFileSync } = require("fs");
        const existing = yaml.load(readFileSync(bookmarksPath, "utf8"));
        if (Array.isArray(existing)) {
          // Remove old "Top Sites" and auto-generated category groups
          const autoCategories = new Set(["Top Sites", ...Object.keys(categorized)]);
          existingBookmarks = existing.filter((group) => {
            const groupName = Object.keys(group)[0];
            return !autoCategories.has(groupName);
          });
        }
      } catch {
        // No existing bookmarks — start fresh
      }
    }

    const finalBookmarks = [...historyBookmarks, ...existingBookmarks];
    const yamlContent = `---\n# Auto-generated by Browser History widget\n# Last updated: ${new Date().toISOString()}\n\n${yaml.dump(finalBookmarks, { lineWidth: -1, quotingType: '"' })}`;

    writeFileSync(bookmarksPath, yamlContent);
    logger.info("Synced %d sites to bookmarks.yaml", topSites.length);

    return res.status(200).json({
      status: "synced",
      topSites: topSites.length,
      categories: Object.keys(categorized),
      bookmarksPath,
    });
  } catch (e) {
    logger.error("Browser history sync error: %s", e.message);
    return res.status(500).json({ error: e.message });
  }
}
